USE [Freshpots]
GO

/****** Object:  Table [dbo].[PotStatus]    Script Date: 8/19/2015 3:04:15 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PotStatus](
	[Id] [smallint] NOT NULL,
	[TextValue] [varchar](50) NOT NULL,
	[AuditModifiedDate] [datetime] NOT NULL CONSTRAINT [DF_PotStatus_AuditModifiedDate]  DEFAULT (getdate()),
 CONSTRAINT [PK_POT_STATUS] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


